### PR TITLE
Add ability to provide a target for links.

### PR DESCRIPTION
**Pull request by InkSpeck**
I found I needed this ability for a mobile app others might find it helpful as well.

### CODE REVIEW

**Comment by johnotander** [comment]
This is awesome!

Do you mind updating the tests to reflect the changes?

**Comment by InkSpeck** [comment]
Done.

**Comment by johnotander** [comment]
Thanks! Published to npm as `ember-linkify@1.1.0`.

**Comment by InkSpeck** [comment]
Nice! thanks for the quick publish.

**Comment by johnotander** [comment]
Not a problem, thanks for the contribution : )

**Pull request merged**
